version: "3"

services:
  chat-app:
    container_name: chat-app
    image: chat-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: unless-stopped
